"""
Django settings for chat_server project.

Generated by 'django-admin startproject' using Django 5.2.8, upgraded to Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import sys

BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / '.env'
load_dotenv(env_path)


SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-8ok2ltjd3k&+mfz0s78m&^ei26)my3&m(5#5ko9+i=kyz_l2j@')

DEBUG = os.getenv('DJANGO_DEBUG', 'False').strip().lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')



INSTALLED_APPS = [
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'api',
    'corsheaders',
    'mcp_client',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'api.middleware.memory_tracker.MemoryTrackerMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Innermost (last): catches @ratelimit(block=True)'s Ratelimited from the view and renders
    # it via RATELIMIT_VIEW (-> 429), so the synthetic response still propagates back out through
    # every outer middleware's response phase (CORS + security headers land on the 429).
    'django_ratelimit.middleware.RatelimitMiddleware',
]

ROOT_URLCONF = 'django_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_config.wsgi.application'


DATABASES = {}

# Cache backend: shared across all gunicorn workers.
# Base/dev default is FileBasedCache (no external service needed for tests).
# Production swaps this to RedisCache in django_config/settings_prod.py so the
# agent-budget counters and django-ratelimit get atomic, cross-worker incr/decr.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.getenv("CACHE_FILE_PATH", "/tmp/fingpt_cache"),
        "TIMEOUT": 3600,  # 1 hour default TTL
        "OPTIONS": {
            "MAX_ENTRIES": 500,
        },
    }
}

# django-ratelimit shares the default cache, so in production its counters live
# in Redis alongside the agent budget (atomic, shared across workers).
RATELIMIT_USE_CACHE = 'default'

# When a request is rate-limited (block=True), RatelimitMiddleware routes the Ratelimited
# exception to this view so the caller gets 429 Too Many Requests + Retry-After, not Django's
# default 403 Forbidden.
RATELIMIT_VIEW = 'api.views.ratelimited'

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_NAME = 'fingpt_sessionid'



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_ALLOWED_ORIGINS = [
    "https://www.tradingview.com",
    "https://tradingview.com",
    "https://www.xyzterminal.com",
    "https://xyzterminal.com",
    "https://www.bloomberg.com",
    "https://bloomberg.com",
    "https://finance.yahoo.com",
]

cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',') if origin.strip()]
    CORS_ALLOWED_ORIGINS.extend(DEFAULT_ALLOWED_ORIGINS)
    CORS_ALLOWED_ORIGINS = list(set(CORS_ALLOWED_ORIGINS))
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOWED_ORIGINS = DEFAULT_ALLOWED_ORIGINS
    CORS_ALLOW_ALL_ORIGINS = DEBUG

CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False').strip().lower() in ('true', '1', 't')
SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False').strip().lower() in ('true', '1', 't')
CSRF_COOKIE_HTTPONLY = True
csrf_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()]

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').strip().lower() in ('true', '1', 't')
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').strip().lower() in ('true', '1', 't')
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True').strip().lower() in ('true', '1', 't')
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
else:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0

SECURE_REDIRECT_EXEMPT = [r'^health/?$']

API_RATE_LIMIT = os.getenv('API_RATE_LIMIT', '600/h')

# News-signals artifact directory (spec §4.4). In prod this is a runtime-
# enforced :ro mount of the heartbeat's signals/ dir ONLY; unset or missing
# path means the endpoint fail-closes to 404 {"error": "no_signals"}.
SIGNALS_DIR = os.getenv('SIGNALS_DIR', '')

# Raw news-items directory (ATL integration Phase B). In prod this is a
# runtime-enforced :ro mount of the heartbeat's digests/ dir ONLY; unset or
# missing path means the endpoint fail-closes to 404 {"error": "no_items"}.
RAW_ITEMS_DIR = os.getenv('RAW_ITEMS_DIR', '')

# Cap on a single items-*.jsonl batch. Deliberately the SAME env var the Heartbeat
# generator reads (news_signals.load_config), so one operator knob moves both
# readers — raising it for the pipeline without raising it here would 404 a batch
# the pipeline happily accepted. Set it in .env.production alongside the
# heartbeat's own env file. The two defaults are pinned together by
# Heartbeat/tests/test_port_parity.py.
RAW_ITEMS_MAX_FILE_MB = int(os.getenv('SIGNALS_MAX_FILE_MB', '10'))

# FinGPT API authentication.
# When FINGPT_API_KEY is set, all /v1/* endpoints require:
#     Authorization: Bearer <FINGPT_API_KEY>
# REQUIRE_FINGPT_API_KEY makes auth fail closed: when True, a MISSING key returns
# HTTP 503 instead of silently disabling authentication. False for local dev;
# settings_prod forces it to True.
FINGPT_API_KEY = os.getenv('FINGPT_API_KEY', '')
REQUIRE_FINGPT_API_KEY = os.getenv('REQUIRE_FINGPT_API_KEY', 'False').strip().lower() in ('true', '1', 't')

# Trusted reverse-proxy peers (P0 Root C.1). get_client_ip() only honors
# X-Real-IP / X-Forwarded-For when REMOTE_ADDR falls inside one of these;
# otherwise it uses REMOTE_ADDR so a direct client cannot spoof its source IP.
# Entries are matched as IP networks: a bare IP is a /32 (or /128) host route
# and a CIDR trusts the whole range -- e.g. set TRUSTED_PROXIES to the podman
# network subnet ('podman network inspect <net>') when a containerized proxy
# reaches the backend through a rootless-Podman SNAT address rather than a
# fixed peer IP. Use the NARROWEST covering CIDR: a public or default-route
# range (0.0.0.0/0, ::/0) would trust every peer and is refused by identity.py.
# A /24 also trusts every OTHER container on that network -- pin the proxy/api
# --ip and trust its /32 to admit only the proxy hop (see production_setup.md
# §6). With a host-service proxy (Variant A) the loopback-only publish is the
# trust boundary (the published-port hop is SNAT'd to the api's own bridge IP);
# with a containerized proxy (Variant B) REMOTE_ADDR is the proxy's real bridge
# IP, so keep this narrow.
TRUSTED_PROXIES = tuple(
    p.strip()
    for p in os.getenv('TRUSTED_PROXIES', '127.0.0.1,::1').split(',')
    if p.strip()
)

WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_MANIFEST_STRICT = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'api.utils.logging_filters.RequestIdFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} [{request_id}] {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {asctime} [{request_id}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if not DEBUG else 'simple',
            'level': 'DEBUG' if DEBUG else 'INFO',
            'filters': ['request_id'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'datascraper': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
